# permissions for end users to view snykmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snykmonitor-viewer-role
rules:
- apiGroups:
  - charts.snyk.io
  resources:
  - snykmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.snyk.io
  resources:
  - snykmonitors/status
  verbs:
  - get
