kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snyk-monitor-rolebinding
subjects:
- kind: ServiceAccount
  name: operand
  namespace: system
roleRef:
  kind: ClusterRole
  name: operand-cluster-role
  apiGroup: rbac.authorization.k8s.io
